### PR TITLE
ISS coordinates - Rounded to 2 decimals

### PR DESCRIPTION
**Pull request by vntrp**

### CODE REVIEW

**Comment by ziad-saab** [comment]
Good solution. Look up the documentation for `Number.prototype.toFixed` to find out an easier way to do this :)

**Comment by vntrp** [comment]
I actually didn't like this solution as it transforms my number into a string...

**Comment by ziad-saab** [comment]
In this case it doesn't matter because you are concatenating a string to the number. So JavaScript will immediately convert it to a string if you don't do it :P

**Comment by vntrp** [comment]
trudat.

**Pull request closed without merging**
